language: node_js
notifications:
  email: edneyroldao@gmail.com
node_js:
  - 0.10
services:
  - mongodb
env:
  global:
    - NODE_ENV: test
addons:
  sauce_connect: true    
before_install:
  - npm install -g bower@1.8.0
  - npm install -g grunt-cli@0.1.13
  - npm install -g karma-cli@0.0.4
  - npm install -g protractor@4.0.11
  - bower install
before_script:
  - node test/data.js
  - grunt
  - cd dist
script:
  - karma start config/karma.config.js --single-run --browsers PhantomJS
  - node server &
  - protractor config/protractor.js